#!/bin/sh

CP='/home/jose/Code/tigerc/lib/sext-0.2.3.jar:/home/jose/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.2.jar:/home/jose/.ivy2/cache/com.github.nikita-volkov/sext/jars/sext-0.2.3.jar:/home/jose/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.10.0.jar:/home/jose/.ivy2/cache/org.scalatest/scalatest_2.11/bundles/scalatest_2.11-2.2.1.jar:/home/jose/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.2.jar:/home/jose/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.2.jar:/home/jose/.ivy2/cache/com.gilt/handlebars-scala_2.11/jars/handlebars-scala_2.11-2.0.1.jar:/home/jose/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.6.4.jar:/home/jose/.ivy2/cache/org.slf4j/slf4j-simple/jars/slf4j-simple-1.6.4.jar:/home/jose/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.1.jar'

TIGER=target/scala-2.11/tigerc_2.11-0.1.jar
GCC=~/src/arm/Sourcery_G++_Lite/bin/arm-none-linux-gnueabi-gcc
RUNTIME=./runtime/

name=$(basename $1 .tig)

rm output/*
java -cp $CP:$TIGER tiger.Tiger $1 output/$name.s
$GCC -march=armv6 -I$RUNTIME/gc/include -g output/$name.s $RUNTIME/runtime.c  $RUNTIME/gc/.libs/libgc.so -o $name
